id = "jasm"
name = "JASM"
version = "0.2.0"
schema_version = 1
description = "JASM language support for Zed."
repository = "https://github.com/josiahbergen/jaide"
authors = ["Josiah Bergen"]
themes = []
icon_themes = []
languages = ["languages/jasm"]
capabilities = []

[lib]

[grammars.jasm]
repository = "file:///Users/josiah/Projects/jaide/.zed/extensions/jasm/grammars/tree-sitter-jasm"
rev = "main"

[language_servers]

[context_servers]

[agent_servers]

[slash_commands]
